# File contains default list of alerts for vmestimator service.
# The alerts below are just recommendations and may require some updates
# and threshold calibration according to every specific setup.
groups:
  - name: 'vmestimator'
    interval: 30s
    rules:
      - alert: 'CardinalityGroupLimitNearlyReached'
        expr: |
          (
            sum(vmestimator_estimator_group_size) by (job, group_by_keys, interval)
            /
            sum(vmestimator_estimator_group_limit) by (job, group_by_keys, interval)
          ) > 0.8
        for: '5m'
        labels:
          severity: 'warning'
        annotations:
          summary: "Cardinality estimate group limit nearly reached for {{ $labels.group_by_keys }}"
          description: >
            The number of tracked groups for group_by_keys={{ $labels.group_by_keys }}
            has reached {{ printf "%.0f%%" (mulf $value 100) }} of the configured
            group_limit.
          
            New groups may soon be rejected.
          
            Consider investigating the source of the cardinality growth and either
            reducing it or increasing group_limit in the stream configuration.

      - alert: 'CardinalityGroupLimitReached'
        expr: 'sum(vmestimator_estimator_group_rejected_size) by (job, group_by_keys, interval) > 0'
        for: '5m'
        labels:
          severity: 'critical'
        annotations:
          summary: "Group limit reached for {{ $labels.group_by_keys }}"
          description: >
            {{ printf "%.0f" $value }} groups for group_by_keys={{ $labels.group_by_keys }}
            cannot be tracked individually because group_limit has been reached.
            
            These groups are being counted in the shared overflow sketch.
            
            Consider investigating the source of the cardinality growth and either
            reducing it or increasing group_limit in the stream configuration.