# File contains default list of alerts for vmestimator service.
# The alerts below are just recommendations and may require some updates
# and threshold calibration according to every specific setup.
groups:
  - name: 'cardinality'
    rules:
      - alert: 'JobCardinalityThresholdExceeded'
        expr: 'max without(instance) (cardinality_estimate{group_by_keys="job"}) > 20000'
        for: '15m'
        labels:
          severity: 'warning'
        annotations:
          dashboard: "{{ $externalURL }}/d/mktd5h8?var-group_by_keys=job&var-interval={{ $labels.interval }}"
          summary: "High cardinality for job {{ $labels.by_job }}"
          description: "Job {{ $labels.by_job }} has {{ $value }} cardinality over the last {{ $labels.interval }}, exceeding the 20000 series threshold."

      - alert: 'CardinalityGroupLimitNearlyReached'
        expr: |
          (
            sum(vmestimator_estimator_group_size) by (job, group_by_keys, interval)
            /
            sum(vmestimator_estimator_group_limit) by (job, group_by_keys, interval)
            * 100
          ) > 80
        for: '15m'
        labels:
          severity: 'warning'
        annotations:
          dashboard: "{{ $externalURL }}/d/mktd5h8?var-group_by_keys{{ $labels.group_by_keys }}=job&var-interval={{ $labels.interval }}"
          summary: "Cardinality estimate group limit nearly reached for {{ $labels.group_by_keys }}"
          description: >
            The number of tracked groups for group_by_keys={{ $labels.group_by_keys }}
            has reached {{ printf "%.0f%%" $value }} of the configured
            group_limit.
            
            New groups may soon be rejected.
            
            Consider investigating the source of the cardinality growth and either
            reducing it or increasing group_limit in the stream configuration.

      - alert: 'CardinalityGroupLimitReached'
        expr: 'sum(vmestimator_estimator_group_rejected_size) by (job, group_by_keys, interval) > 0'
        for: '5m'
        labels:
          severity: 'critical'
        annotations:
          dashboard: "{{ $externalURL }}/d/mktd5h8?var-group_by_keys{{ $labels.group_by_keys }}=job&var-interval={{ $labels.interval }}"
          summary: "Group limit reached for {{ $labels.group_by_keys }}"
          description: >
            {{ printf "%.0f" $value }} groups for group_by_keys={{ $labels.group_by_keys }}
            cannot be tracked individually because group_limit has been reached.
            
            Consider investigating the source of the cardinality growth and either
            reducing it or increasing group_limit in the stream configuration.