{
 "title": "VictoriaMetrics - Cardinality Explorer",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(cardinality_estimate,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(cardinality_estimate{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "interval",
    "query": {
     "query": "label_values(cardinality_estimate,interval)"
    }
   },
   {
    "name": "group_by_keys",
    "query": {
     "query": "label_values(cardinality_estimate{interval=~\"$interval\", group_by_keys!=\"__global__\", group_by_keys!=\"__group__\"},group_by_keys)"
    }
   },
   {
    "name": "group_by_values",
    "query": {
     "query": "label_values(cardinality_estimate{interval=~\"$interval\", group_by_keys=~\"$group_by_keys\"},group_by_values)"
    }
   },
   {
    "name": "churn_short",
    "query": {
     "query": "label_values(cardinality_estimate,interval)"
    }
   },
   {
    "name": "churn_long",
    "query": {
     "query": "label_values(cardinality_estimate,interval)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global Cardinality",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    max(cardinality_estimate{job=~\"$job\",instance=~\"$instance\",group_by_keys=~\"__global__\",interval=~\"$interval\"}) without(instance)\n) by (interval)\n\n",
     "legendFormat": "{{interval}}"
    }
   ]
  },
  {
   "title": "Global Churn ($churn_short - $churn_long)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum(\n        max(cardinality_estimate{\n            job=~\"$job\",\n            instance=~\"$instance\",\n            group_by_keys=\"__global__\",\n            interval=\"$churn_long\"\n        }) without (instance)\n    ) by (group_by_keys,group_by_values)\n    -\n    sum(\n        max(cardinality_estimate{\n            job=~\"$job\",\n            instance=~\"$instance\",\n            group_by_keys=\"__global__\",\n            interval=\"$churn_short\"\n        }) without (instance)\n    ) by (group_by_keys,group_by_values)\n)\n/\nsum(\n    max(cardinality_estimate{\n        job=~\"$job\",\n        instance=~\"$instance\",\n        group_by_keys=\"__global__\",\n        interval=\"$churn_long\"\n    }) without (instance)\n) by (group_by_keys,group_by_values)\n* 100",
     "legendFormat": "{{interval}}"
    }
   ]
  },
  {
   "title": "Group Keys Cardinality Limit Usage %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(cardinality_estimate{job=~\"$job\",instance=~\"$instance\",interval=~\"$interval\",group_by_keys=~\"__group__\",group_by_values=~\"$group_by_keys\"}) without (instance)\n/\nmax(vmestimator_estimator_group_limit{job=~\"$job\",instance=~\"$instance\",interval=~\"$interval\",group_by_values=~\"$group_by_keys\"}) without(instance)",
     "legendFormat": "{{group_by_values}} ({{interval}})"
    }
   ]
  },
  {
   "title": "Group Keys Cardinality",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    max(cardinality_estimate{job=~\"$job\",instance=~\"$instance\",interval=~\"$interval\",group_by_keys=~\"__group__\"}) without (instance)\n) by (interval,group_by_values)",
     "legendFormat": "{{group_by_values}} ({{interval}})"
    }
   ]
  },
  { "title": "Group: $group_by_keys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }, "repeat": "group_by_keys" },
  {
   "title": " Top 10 Cardinality of $group_by_keys",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(\n    10, \n    sum(\n        max(\n            cardinality_estimate{job=~\"$job\",instance=~\"$instance\",interval=~\"$interval\",group_by_keys=~\"$group_by_keys\",group_by_keys!=\"__global__\",group_by_keys!=\"__group__\",group_by_values=~\"$group_by_values\"}) without (instance)\n    ) by (group_by_values,interval)\n)",
     "legendFormat": "{{group_by_values}} ({{interval}})"
    }
   ]
  },
  {
   "title": "Top 10 Churn ($churn_short - $churn_long)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(\n    10,\n    (\n        sum(\n            max(cardinality_estimate{\n                job=~\"$job\",\n                instance=~\"$instance\",\n                group_by_keys=~\"$group_by_keys\",\n                group_by_keys!=\"__global__\",\n                group_by_keys!=\"__group__\",\n                group_by_values=~\"$group_by_values\",\n                interval=\"$churn_long\"\n            }) without (instance)\n        ) by (group_by_keys,group_by_values)\n        -\n        sum(\n            max(cardinality_estimate{\n                job=~\"$job\",\n                instance=~\"$instance\",\n                group_by_keys=~\"$group_by_keys\",\n                group_by_keys!=\"__global__\",\n                group_by_keys!=\"__group__\",\n                group_by_values=~\"$group_by_values\",\n                interval=\"$churn_short\"\n            }) without (instance)\n        ) by (group_by_keys,group_by_values)\n    )\n    /\n    sum(\n        max(cardinality_estimate{\n            job=~\"$job\",\n            instance=~\"$instance\",\n            group_by_keys=~\"$group_by_keys\",\n            group_by_keys!=\"__global__\",\n            group_by_keys!=\"__group__\",\n            group_by_values=~\"$group_by_values\",\n            interval=\"$churn_long\"\n        }) without (instance)\n    ) by (group_by_keys,group_by_values) * 100\n)",
     "legendFormat": "{{interval}}"
    }
   ]
  }
 ]
}